@echo off
rem Pre-build step: regenerate the git revision header used by the About page.
rem %1 = project directory (with trailing backslash)

setlocal
set "OUT=%~1..\..\include\GitVersion.h"
set "TMP=%OUT%.tmp"

rem Resolve the revision: exact tag when HEAD is tagged, otherwise the short commit hash.
for /f "delims=" %%i in ('git describe --tags --exact-match 2^>nul') do set "REV=%%i"
if not defined REV (
    for /f "delims=" %%i in ('git rev-parse --short HEAD 2^>nul') do set "REV=%%i"
)
if not defined REV set "REV=unknown"

rem Mark the build as dirty when the working tree has uncommitted changes.
set "DIRTY="
git diff-index --quiet HEAD -- 2>nul
if errorlevel 1 set "DIRTY=-dirty"

rem Only rewrite the header when the contents actually changed, so dependent
rem objects are not rebuilt on every compile.
> "%TMP%" echo #pragma once
>>"%TMP%" echo.
>>"%TMP%" echo // Generated by tools\gen_git_version.cmd - do not edit.
>>"%TMP%" echo #define GIT_REVISION "%REV%%DIRTY%"

fc /b "%TMP%" "%OUT%" >nul 2>&1
if errorlevel 1 (
    copy /y "%TMP%" "%OUT%" >nul
    echo GitVersion.h: %REV%%DIRTY%
)
del "%TMP%" >nul 2>&1

endlocal
exit /b 0
